version: '3.8'
services:
  node:
    image: consensys/teku:22.5.1
    hostname: node
    restart: always
    user: root
    command: |
      --network=gnosis
      --eth1-endpoints=$XDAI_RPC_URL
      --p2p-udp-port=12000
      --p2p-port=13000
      --p2p-advertised-ip=$PUBLIC_IP
      --p2p-peer-lower-bound=$LOWER_BOUND_PEERS
      --p2p-peer-upper-bound=$UPPER_BOUND_PEERS
      --data-path=/opt/teku/db
      --metrics-enabled
      --metrics-host-allowlist=*
      --initial-state=$GBC_RPC_URL/eth/v2/debug/beacon/states/finalized
      --logging=$LOG_LEVEL
      --validator-keys=/opt/teku/keys/validator_keys:/opt/teku/keys/passwords
      --validators-graffiti=${OVERRIDE_GRAFFITI:-Teku/v22.5.1-8f97fa5}
    environment:
      JAVA_OPTS: "-Dteku.portableBlst=false"
    ports:
      - '12000:12000/udp'
      - '13000:13000'
    volumes:
      - ./node_db:/opt/teku/db
      - ./keys:/opt/teku/keys
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
  validator-import-slashing-protection:
    image: consensys/teku:22.5.1
    user: root
    command: |
      slashing-protection import
      --data-path=/opt/teku/db
      --from=/opt/teku/config/slashing_protection.json
    volumes:
      - ./config:/opt/teku/config
      - ./node_db:/opt/teku/db
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  validator-export-slashing-protection:
    image: consensys/teku:22.5.1
    user: root
    command: |
      slashing-protection export
      --data-path=/opt/teku/db
      --to=/opt/teku/config/slashing_protection.json
    volumes:
      - ./config:/opt/teku/config
      - ./node_db:/opt/teku/db
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  prometheus:
    image: prom/prometheus:latest
    restart: always
    command: |
      --web.listen-address=0.0.0.0:9090
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      - type: bind
        source: ./prometheus/scrape-targets
        target: /prometheus/targets
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
volumes:
  prometheus-data:
